//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pilotos
    {
        [Key]
        public int codigo { get; set; }
        [Required][Display(Name ="Nombre Completo")][StringLength(200,MinimumLength =0)]
        public string nombre { get; set; }
        [Display(Name ="Horas de vuelo")]
        public System.TimeSpan horas_de_vuelo { get; set; }
    }
}
